/**
 * The server-side builder — one generated patch source string in, one Obsidian-loadable
 * `main.js` out, entirely in memory.
 *
 * Nothing touches the filesystem here. esbuild is driven with `stdin` + `write: false`, so the bytes
 * exist only as a string until they have been validated, hashed and signed. An artifact that reaches
 * disk before it is signed is an artifact something can pick up and install.
 *
 * ## The three things that make this build Obsidian's build and not a generic bundle
 *
 * 1. **`format: 'cjs'` with `obsidian` external.** The host evaluates a plugin's CJS with a `require`
 *    the host controls, so a bare `require("obsidian")` resolves to the *running app's* module —
 *    which is precisely why `Workspace.prototype` in a mod is the live prototype and why patch
 *    handles are minification-proof.
 * 2. **`platform: 'browser'`, never `'node'`.** A mod declares `isDesktopOnly: false` and arrives on
 *    mobile by vault sync, where Obsidian is a Capacitor WebView with no node at all. `'node'` would
 *    quietly shim node builtins into a bundle that then throws on a phone.
 * 3. **The external list carries the `node:`-prefixed variants of every builtin.** MEASURED: esbuild
 *    does *not* treat `external: [...builtinModules]` as covering `node:`-prefixed specifiers, so
 *    `import "node:fs"` fails the build outright while bare `"path"` builds fine. Generated code is
 *    forbidden from using the prefix at all (the validator's `import-not-allowed` rule), and the
 *    external list covers it anyway — the failure mode of getting this wrong is a build error whose
 *    message points at node rather than at the rule that was broken.
 *
 * ## Why the emitted shape is asserted
 *
 * Obsidian loads a plugin by evaluating its CJS and reading `module.exports.default`. esbuild
 * produces that as `__export(main_exports, { default: () => X })` followed by
 * `module.exports = __toCommonJS(main_exports)`. A build that *succeeds* while emitting some other
 * shape — an ESM bundle, an IIFE, a module whose default export was tree-shaken away — fails at
 * `enablePlugin()` time with nothing useful in the console. That is the worst possible place for it
 * to fail, so {@link assertObsidianShape} refuses the artifact here instead, where the message can
 * say what was actually wrong.
 */

import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { builtinModules } from 'node:module';

import esbuild from 'esbuild';

/* ────────────────────────────────────────────────────────────────────────────
 * Build policy
 * ──────────────────────────────────────────────────────────────────────────── */

/**
 * The Obsidian sample plugin's external list, plus the `node:`-prefixed variant of every builtin.
 *
 * `obsidian` and `electron` are supplied by the host. The CodeMirror and Lezer packages are the ones
 * Obsidian itself bundles and re-exposes, so a plugin that imports them must get the host's copy or
 * it ends up with two incompatible editor states.
 */
export const OBSIDIAN_EXTERNAL: readonly string[] = Object.freeze([
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  ...builtinModules,
  ...builtinModules.map((m) => `node:${m}`),
]);

/** Specifiers a generated mod's bundle is allowed to still `require()` at runtime. */
const RUNTIME_REQUIRE_ALLOWED: ReadonlySet<string> = new Set([
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
]);

const BANNER =
  '/* Generated by modkit. Do not edit — regenerate from the stored request instead.\n' +
  '   This is a modkit mod: it patches another plugin through Obsidian\'s public API and never\n' +
  '   modifies that plugin\'s own files. Disable it in Settings → Community plugins to remove it. */\n';

/**
 * Where `monkey-around` is resolved from.
 *
 * `resolveDir` is required whenever a `stdin` source imports anything bundleable, and pointing it at
 * the template directory is what makes that directory stand for the dependency allowlist. The
 * allowlist is *enforced* by the validator's `import-not-allowed` rule — this is the second half of
 * the same fence, not a substitute for it.
 */
const DEFAULT_RESOLVE_DIR = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../..',
  'templates/patch',
);

/* ────────────────────────────────────────────────────────────────────────────
 * Types
 * ──────────────────────────────────────────────────────────────────────────── */

export interface BuildMessage {
  text: string;
  file?: string;
  line?: number;
  column?: number;
  /** The offending source line, when esbuild reported one. */
  excerpt?: string;
}

export interface BuildPatchPluginOptions {
  /**
   * Directory bare specifiers resolve from. Defaults to `templates/patch` next to this
   * package; override in a test that wants a different dependency set.
   */
  resolveDir?: string;
  /** `'js'` for generated mods (the model emits plain JS); `'ts'` for the hand-written template. */
  loader?: 'js' | 'ts';
  /** The name locations are reported against. */
  sourcefile?: string;
  /**
   * Default `false`, and that is a product decision rather than a build one: a user can open a mod's
   * `main.js` and read what was installed into their vault. Generated code that cannot be read is
   * generated code that cannot be trusted.
   */
  minify?: boolean;
  /** Replaces the default modkit banner. Pass `''` for none. */
  banner?: string;
  /** Replaces {@link OBSIDIAN_EXTERNAL} wholesale. Rarely wanted. */
  external?: readonly string[];
}

export interface BuildFailure {
  ok: false;
  errors: BuildMessage[];
  warnings: BuildMessage[];
}

export interface BuildSuccess {
  ok: true;
  /** The whole `main.js`, verbatim. This is what gets signed and written into the vault. */
  code: string;
  /** Lowercase hex SHA-256 of `utf8(code)` — the digest that travels in the signed payload. */
  sha256: string;
  /** Byte length of `code`, not its `.length`: a multi-byte character is one character, three bytes. */
  bytes: number;
  warnings: BuildMessage[];
  /** Module paths esbuild actually inlined, from the metafile. `monkey-around` should be among them. */
  inlined: string[];
  /** Specifiers left as runtime `require()` calls — `obsidian`, and normally nothing else. */
  externals: string[];
}

export type BuildResult = BuildSuccess | BuildFailure;

/* ────────────────────────────────────────────────────────────────────────────
 * Build
 * ──────────────────────────────────────────────────────────────────────────── */

/**
 * Bundle one generated patch.
 *
 * Never throws: an esbuild failure, a shape violation and an internal error all come back as
 * `{ ok: false, errors }`, because a build failure is an ordinary job outcome and a daemon that
 * throws on one turns a rejected generation into a restart.
 */
export async function buildPatchPlugin(
  source: string,
  options: BuildPatchPluginOptions = {},
): Promise<BuildResult> {
  const resolveDir = options.resolveDir ?? DEFAULT_RESOLVE_DIR;
  const loader = options.loader ?? 'js';
  const sourcefile = options.sourcefile ?? `main.${loader}`;
  const banner = options.banner ?? BANNER;
  const external = [...(options.external ?? OBSIDIAN_EXTERNAL)];

  let result: esbuild.BuildResult<{ write: false; metafile: true }>;
  try {
    result = await esbuild.build({
      stdin: { contents: source, loader, sourcefile, resolveDir },
      bundle: true,
      format: 'cjs',
      // NOT 'node': a mod declares isDesktopOnly false and runs in a Capacitor WebView on mobile.
      platform: 'browser',
      target: 'es2021',
      external,
      treeShaking: true,
      minify: options.minify ?? false,
      // Readable output, and no \u escapes for ordinary text — a user may well read this file.
      charset: 'utf8',
      // No sourcemap ships: the source of truth for a mod is the stored request, not a map pointing
      // at a string that only ever existed inside a daemon process.
      sourcemap: false,
      legalComments: 'none',
      ...(banner === '' ? {} : { banner: { js: banner } }),
      write: false,
      // Errors come back on the result rather than onto the daemon's stderr, where they would be
      // interleaved with every other job.
      logLevel: 'silent',
      metafile: true,
    });
  } catch (err) {
    // esbuild throws on a *configuration* error rather than a compile error; it carries the same
    // message array, so unwrap it and keep the shape callers already handle.
    const e = err as { errors?: esbuild.Message[]; warnings?: esbuild.Message[]; message?: string };
    if (Array.isArray(e.errors) && e.errors.length > 0) {
      return {
        ok: false,
        errors: e.errors.map(toBuildMessage),
        warnings: (e.warnings ?? []).map(toBuildMessage),
      };
    }
    return { ok: false, errors: [{ text: e.message ?? String(err) }], warnings: [] };
  }

  const warnings = result.warnings.map(toBuildMessage);
  if (result.errors.length > 0) {
    return { ok: false, errors: result.errors.map(toBuildMessage), warnings };
  }

  const output = result.outputFiles?.[0];
  if (!output) {
    return { ok: false, errors: [{ text: 'esbuild produced no output file' }], warnings };
  }
  const code = output.text;

  const shapeErrors = assertObsidianShape(code);
  if (shapeErrors.length > 0) return { ok: false, errors: shapeErrors, warnings };

  return {
    ok: true,
    code,
    sha256: sha256Hex(code),
    bytes: Buffer.byteLength(code, 'utf8'),
    warnings,
    inlined: Object.keys(result.metafile?.inputs ?? {}),
    externals: requiredSpecifiers(code),
  };
}

/**
 * Assert the bundle is the shape Obsidian actually loads.
 *
 * Everything checked here is cheap, and every one of them is a failure that would otherwise appear
 * as "the plugin did nothing when enabled" with an empty console:
 *
 * - `module.exports = __toCommonJS(X)` — the CJS handoff. Absent means the format was wrong.
 * - `X` carries a `default` key — Obsidian instantiates `module.exports.default`. A bundle that
 *   exports everything *except* `default` enables cleanly and constructs nothing.
 * - no runtime `require()` of anything but the host-supplied packages. A `require("node:fs")` or a
 *   `require("monkey-around")` surviving into the bundle is a mod that throws on load, and on mobile
 *   it throws for a reason the user cannot act on.
 */
export function assertObsidianShape(code: string): BuildMessage[] {
  const errors: BuildMessage[] = [];

  const handoff = /module\.exports\s*=\s*__toCommonJS\(\s*([A-Za-z0-9_$]+)\s*\)/.exec(code);
  if (!handoff) {
    errors.push({
      text:
        'the bundle does not end in `module.exports = __toCommonJS(...)`, so Obsidian has nothing ' +
        'to load — check that format is "cjs" and that the source has a default export',
    });
  } else {
    const exportsId = handoff[1] ?? '';
    const exportMap = new RegExp(
      `__export\\(\\s*${escapeRegExp(exportsId)}\\s*,\\s*\\{([^}]*)\\}`,
    ).exec(code);
    const body = exportMap?.[1] ?? '';
    if (!/\bdefault\s*:/.test(body)) {
      errors.push({
        text:
          'the bundle exports no `default`, so Obsidian enables the plugin and instantiates nothing — ' +
          'the source must `export default class ... extends Plugin`',
      });
    }
  }

  for (const spec of requiredSpecifiers(code)) {
    if (RUNTIME_REQUIRE_ALLOWED.has(spec)) continue;
    errors.push({
      text:
        `the bundle still require()s "${spec}" at runtime — only host-supplied packages may stay ` +
        'external, and a node builtin is not available in Obsidian mobile at all',
    });
  }

  return errors;
}

/** Every specifier the bundle still resolves at runtime. */
function requiredSpecifiers(code: string): string[] {
  const found = new Set<string>();
  const re = /\brequire\(\s*(["'])((?:(?!\1).)*)\1\s*\)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(code)) !== null) {
    const spec = m[2];
    if (spec !== undefined) found.add(spec);
  }
  return [...found].sort();
}

/** Lowercase hex SHA-256 of the UTF-8 bytes. The digest the signed payload carries. */
export function sha256Hex(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/**
 * One human-readable block for a `JobError.detail`.
 *
 * esbuild's own `formatMessages` is async and spawns work in the service; this is synchronous and
 * good enough for a log line, which is where these end up.
 */
export function formatBuildMessages(messages: readonly BuildMessage[]): string {
  return messages
    .map((m) => {
      const where = m.file !== undefined ? `${m.file}:${m.line ?? 0}:${m.column ?? 0}: ` : '';
      const excerpt = m.excerpt !== undefined && m.excerpt !== '' ? `\n    ${m.excerpt}` : '';
      return `${where}${m.text}${excerpt}`;
    })
    .join('\n');
}

/**
 * Stop esbuild's child process.
 *
 * The Go binary starts once per node process and every `esbuild.build()` reuses it, which is the
 * whole reason not to shell out to the CLI per job. It also keeps the process alive, so a daemon
 * shutdown that does not call this waits for its own hard-exit timer.
 */
export async function stopBuilder(): Promise<void> {
  try {
    await esbuild.stop();
  } catch {
    /* shutting down is not a place to fail */
  }
}

function toBuildMessage(message: esbuild.Message): BuildMessage {
  const loc = message.location;
  return {
    text: message.text,
    ...(loc?.file === undefined ? {} : { file: loc.file }),
    ...(loc?.line === undefined ? {} : { line: loc.line }),
    ...(loc?.column === undefined ? {} : { column: loc.column + 1 }),
    ...(loc?.lineText === undefined || loc.lineText === ''
      ? {}
      : { excerpt: loc.lineText.trim().slice(0, 200) }),
  };
}

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
