// Build the modkit plugin. The sample-plugin convention, with two deliberate deltas:
//
//   1. Output goes to plugin/dist/ rather than the repo root, because scripts/install-to-vault.mjs
//      copies dist/{main.js,manifest.json,styles.css} into the vault. This repo is not itself
//      cloned into .obsidian/plugins/.
//   2. `external` also carries the node:-prefixed builtins. MEASURED (brief-build-convention §1):
//      builtinModules lists almost everything bare — zero prefixed names on Node 22, four on Node
//      24 — so `import "node:fs"` fails the build outright while bare "fs" resolves. Listing both
//      spellings makes the failure impossible, on either runtime.

import { builtinModules } from 'node:module'
import { copyFile, mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import process from 'node:process'
import esbuild from 'esbuild'

const ROOT = dirname(fileURLToPath(import.meta.url))
const OUT = join(ROOT, 'dist')

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
modkit — https://github.com/andrewschreiber/modkit-plugin
*/
`

// modkit's own chrome is injected at runtime by injectUiStyles()/injectPickerStyles(), because a
// body-wide `cursor: crosshair` must not be live outside pick mode. styles.css exists so the
// install path has the file it expects and so a user can add vault-local overrides.
const STYLES = `/* modkit
 *
 * modkit injects its stylesheets at runtime (plugin/src/ui/ui.css.ts and
 * plugin/src/picker/picker.css.ts), each marked with data-modkit-style, so that the picker's
 * global cursor rules only exist while a pick session is open. This file is intentionally empty
 * apart from this note; rules added here are loaded by Obsidian for the life of the plugin.
 */
`

const prod = process.argv[2] === 'production'

/** manifest.json and styles.css must land in dist/ on every build, watch included. */
async function emitAssets() {
  await mkdir(OUT, { recursive: true })
  await copyFile(join(ROOT, 'manifest.json'), join(OUT, 'manifest.json'))
  await writeFile(join(OUT, 'styles.css'), STYLES, 'utf8')
}

const options = {
  banner: { js: banner },
  entryPoints: [join(ROOT, 'src', 'main.ts')],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: join(OUT, 'main.js'),
  // Never minified, in either mode. DESIGN §6 makes auditability the open trust gap for generated
  // code, and a tool that asks users to read what it installed has to be readable itself. A patch
  // host is a few hundred KB; size is not a constraint here.
  minify: false,
}

await emitAssets()

if (prod) {
  await esbuild.build(options)
  process.exit(0)
} else {
  const context = await esbuild.context(options)
  await context.watch()
}
